let products = [
	{
		"productID": 1,
		"productName": "Chai",
		"supplierID": 1,
		"categoryID": 1,
		"quantityPerUnit": "10 boxes x 20 bags",
		"unitPrice": 18,
		"unitsInStock": 39,
		"unitsOnOrder": 0,
		"reorderLevel": 10,
		"discontinued": false,
		"categoryID": 1,
		"categoryName": "Beverages",
		"supplierID": 1,
		"companyName": "Exotic Liquids",
	},
	{
		"productID": 2,
		"productName": "Chang",
		"supplierID": 1,
		"categoryID": 1,
		"quantityPerUnit": "24 - 12 oz bottles",
		"unitPrice": 19,
		"unitsInStock": 17,
		"unitsOnOrder": 40,
		"reorderLevel": 25,
		"discontinued": false,
		"categoryID": 1,
		"categoryName": "Beverages",
		"supplierID": 1,
		"companyName": "Exotic Liquids"
	},
	{
		"productID": 3,
		"productName": "Aniseed Syrup",
		"supplierID": 1,
		"categoryID": 2,
		"quantityPerUnit": "12 - 550 ml bottles",
		"unitPrice": 10,
		"unitsInStock": 13,
		"unitsOnOrder": 70,
		"reorderLevel": 25,
		"discontinued": false,
		"categoryID": 2,
		"categoryName": "Condiments",
		"supplierID": 1,
		"companyName": "Exotic Liquids"
	},
	{
		"productID": 4,
		"productName": "Chef Anton's Cajun Seasoning",
		"supplierID": 2,
		"categoryID": 2,
		"quantityPerUnit": "48 - 6 oz jars",
		"unitPrice": 22,
		"unitsInStock": 53,
		"unitsOnOrder": 0,
		"reorderLevel": 0,
		"discontinued": false,
		"categoryID": 2,
		"categoryName": "Condiments",
		"supplierID": 2,
		"companyName": "New Orleans Cajun Delights"
	},
	{
		"productID": 5,
		"productName": "Chef Anton's Gumbo Mix",
		"supplierID": 2,
		"categoryID": 2,
		"quantityPerUnit": "36 boxes",
		"unitPrice": 21.35,
		"unitsInStock": 0,
		"unitsOnOrder": 0,
		"reorderLevel": 0,
		"discontinued": true,
		"categoryID": 2,
		"categoryName": "Condiments",
		"supplierID": 2,
		"companyName": "New Orleans Cajun Delights"
	},
	{
		"productID": 6,
		"productName": "Grandma's Boysenberry Spread",
		"supplierID": 3,
		"categoryID": 2,
		"quantityPerUnit": "12 - 8 oz jars",
		"unitPrice": 25,
		"unitsInStock": 120,
		"unitsOnOrder": 0,
		"reorderLevel": 25,
		"discontinued": false,
		"categoryID": 2,
		"categoryName": "Condiments",
		"supplierID": 3,
		"companyName": "Grandma Kelly's Homestead"
	},
	{
		"productID": 7,
		"productName": "Uncle Bob's Organic Dried Pears",
		"supplierID": 3,
		"categoryID": 7,
		"quantityPerUnit": "12 - 1 lb pkgs.",
		"unitPrice": 30,
		"unitsInStock": 15,
		"unitsOnOrder": 0,
		"reorderLevel": 10,
		"discontinued": false,
		"categoryID": 7,
		"categoryName": "Produce",
		"supplierID": 3,
		"companyName": "Grandma Kelly's Homestead"
	},
	{
		"productID": 8,
		"productName": "Northwoods Cranberry Sauce",
		"supplierID": 3,
		"categoryID": 2,
		"quantityPerUnit": "12 - 12 oz jars",
		"unitPrice": 40,
		"unitsInStock": 6,
		"unitsOnOrder": 0,
		"reorderLevel": 0,
		"discontinued": false,
		"categoryID": 2,
		"categoryName": "Condiments",
		"supplierID": 3,
		"companyName": "Grandma Kelly's Homestead"
	},
	{
		"productID": 9,
		"productName": "Mishi Kobe Niku",
		"supplierID": 4,
		"categoryID": 6,
		"quantityPerUnit": "18 - 500 g pkgs.",
		"unitPrice": 97,
		"unitsInStock": 29,
		"unitsOnOrder": 0,
		"reorderLevel": 0,
		"discontinued": true,
		"categoryID": 6,
		"categoryName": "Meat/Poultry",
		"supplierID": 4,
		"companyName": "Tokyo Traders"
	},
	{
		"productID": 10,
		"productName": "Ikura",
		"supplierID": 4,
		"categoryID": 8,
		"quantityPerUnit": "12 - 200 ml jars",
		"unitPrice": 31,
		"unitsInStock": 31,
		"unitsOnOrder": 0,
		"reorderLevel": 0,
		"discontinued": false,
		"categoryID": 8,
		"categoryName": "Seafood",
		"supplierID": 4,
		"companyName": "Tokyo Traders"
	},
	{
		"productID": 11,
		"productName": "Queso Cabrales",
		"supplierID": 5,
		"categoryID": 4,
		"quantityPerUnit": "1 kg pkg.",
		"unitPrice": 21,
		"unitsInStock": 22,
		"unitsOnOrder": 30,
		"reorderLevel": 30,
		"discontinued": false,
		"categoryID": 4,
		"categoryName": "Dairy Products",
		"supplierID": 5,
		"companyName": "Cooperativa de Quesos 'Las Cabras'"
	}];